Description: >
  Carlos Rivas / Udacity
  This template deploys a VPC, with a pair of public and private subnets spread
  across two Availabilty Zones. It deploys an Internet Gateway, with a default
  route on the public subnets. It deploys a pair of NAT Gateways (one in each AZ),
  and default routes for them in the private subnets.

Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String
Resources:
  #instace profile contains the IAM Role name(s) that we want to associate to our auto scaling EC2 Servers
  ProfileWithRolesForOurApp:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - UdacityS3ReadOnlyEC2

Outputs:
    #Bonus points for useful outputs!
    ProfileWithRolesForOurApp:
      Description: A reference to IAM role
      Value: !Ref ProfileWithRolesForOurApp
      Export:
        Name: !Sub ${EnvironmentName}-ProfileWithRoles